[project]
name = "nlp-term-7"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10.12"
dependencies = [
    "autoawq>=0.2.9",
    "bs4>=0.0.2",
    "gradio>=5.34.0",
    "selenium>=4.33.0",
    "transformers>=4.52.4",
]
